### ISSUE TITLE
track and elevator crash

### ISSUE THREAD

**Issue by PRavenhold** [Emasher/EmashersMods#113]
1 button and 1 elevator or 1 track
adjust channels
press button 
CRASH!

---- Minecraft Crash Report ----
// Why did you do that?

Time: 11/2/14 11:39 PM
Description: Ticking memory connection

java.lang.NullPointerException
	at emasher.api.Util.moveBlock(Util.java:216)
	at emasher.api.Util.moveBlock(Util.java:208)
	at emasher.sockets.UtilScala$.moveGroup(UtilScala.scala:29)
	at emasher.sockets.modules.ModElevator.onRSInterfaceChange(ModElevator.scala:76)
	at emasher.sockets.TileSocket.modifyRS(TileSocket.java:569)
	at emasher.sockets.modules.ModButton.onSideActivated(ModButton.java:95)
	at emasher.api.SocketModule.onSideActivated(SocketModule.java:214)
	at emasher.sockets.BlockSocket.func_71903_a(BlockSocket.java:286)
	at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:421)
	at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:556)
	at net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
	at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
	at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
	at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
	at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:109)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at emasher.api.Util.moveBlock(Util.java:216)
	at emasher.api.Util.moveBlock(Util.java:208)
	at emasher.sockets.UtilScala$.moveGroup(UtilScala.scala:29)
	at emasher.sockets.modules.ModElevator.onRSInterfaceChange(ModElevator.scala:76)
	at emasher.sockets.TileSocket.modifyRS(TileSocket.java:569)
	at emasher.sockets.modules.ModButton.onSideActivated(ModButton.java:95)
	at emasher.api.SocketModule.onSideActivated(SocketModule.java:214)
	at emasher.sockets.BlockSocket.func_71903_a(BlockSocket.java:286)
	at net.minecraft.item.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:421)
	at net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:556)
	at net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
	at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
	at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetServerHandler@3be6197e
Stacktrace:
	at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
	at net.minecraft.server.integrated.IntegratedServerListenThread.func_71747_b(IntegratedServerListenThread.java:109)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 279537472 bytes (266 MB) / 3597139968 bytes (3430 MB) up to 3817865216 bytes (3641 MB)

**Comment by Emasher** [comment]
1.6.4 versions are no longer supported.
