### ISSUE TITLE
No class found crash with beta5

### ISSUE THREAD

**Issue by Landstryder** [Emasher/EmashersMods#130]
I'm getting this crash with the 1.2.0.5-BETA

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 6/1/15 8:39 AM
Description: Initializing game

java.lang.NoClassDefFoundError: emasher/sockets/modules/ModTankDisplay
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: emasher.sockets.modules.ModTankDisplay
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.UnsupportedClassVersionError: emasher/sockets/modules/ModTankDisplay : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_75, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 701057576 bytes (668 MB) / 1613234176 bytes (1538 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.104.1360 Minecraft Forge 10.13.3.1360 122 mods loaded, 121 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.104.1360} [Forge Mod Loader] (forge-1.7.10-10.13.3.1360-1.7.10-universal.jar) Unloaded->Constructed
	Forge{10.13.3.1360} [Minecraft Forge] (forge-1.7.10-10.13.3.1360-1.7.10-universal.jar) Unloaded->Constructed
	appliedenergistics2-core{rv2-stable-3} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed
	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) Unloaded->Constructed
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed
	StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) Unloaded->Constructed
	AccidentallyCircumstantialEvents{1.6.0} [Accidentally Circumstantial Events] (accidentallycircumstantialevents-1.6.0.jar) Unloaded->Constructed
	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) Unloaded->Constructed
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed
	appliedenergistics2{rv2-stable-3} [Applied Energistics 2] (appliedenergistics2-rv2-stable-3.jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed
	asielib{0.4.1} [asielib] (AsieLib-1.7.10-0.4.1.jar) Unloaded->Constructed
	bdlib{1.8.1.87} [BD Lib] (bdlib-1.8.1.87-mc1.7.10.jar) Unloaded->Constructed
	betterrecords{1.7.10-1.1.9} [Better Records] (betterrecords-1.7.10-1.1.9.jar) Unloaded->Constructed
	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) Unloaded->Constructed
	Forestry{3.5.6.15} [Forestry for Minecraft] (forestry_1.7.10-3.5.6.15.jar) Unloaded->Constructed
	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed
	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) Unloaded->Constructed
	BinnieCore{2.0-pre8} [Binnie Core] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
	Botany{2.0-pre8} [Botany] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
	ExtraBees{2.0-pre8} [Extra Bees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
	ExtraTrees{2.0-pre8} [Extra Trees] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
	Genetics{2.0-pre8} [Genetics] (binnie-mods-2.0-pre8.jar) Unloaded->Constructed
	BiomeTweaker{0.9.97} [BiomeTweaker] (BiomeTweaker-1.7.10-0.9.97.jar) Unloaded->Constructed
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed
	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed
	ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded->Constructed
	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) Unloaded->Constructed
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	Mekanism{8.1.3} [Mekanism] (Mekanism-1.7.10-8.1.3.231.jar) Unloaded->Constructed
	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) Unloaded->Constructed
	MrTJPCoreMod{1.0.8.16} [MrTJPCore] (MrTJPCore-1.7.10-1.0.8.16-universal.jar) Unloaded->Constructed
	ProjRed|Core{4.6.2.82} [ProjectRed] (ProjectRed-1.7.10-4.6.2.82-Base.jar) Unloaded->Constructed
	ProjRed|Transmission{4.6.2.82} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.6.2.82-Integration.jar) Unloaded->Constructed
	OpenComputers{1.5.12.26} [OpenComputers] (OpenComputers-MC1.7.10-1.5.12.26-universal.jar) Unloaded->Constructed
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed
	computronics{1.5.1} [Computronics] (Computronics-1.7.10-1.5.1.jar) Unloaded->Constructed
	CustomChestLoot{1.1.1} [Custom Chest Loot] (CustomChestLoot-1.7.10-1.1.1.jar) Unloaded->Constructed
	CustomMainMenu{1.5} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.5.jar) Unloaded->Constructed
	CustomOreGen{1.2.18} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.18.jar) Unloaded->Constructed
	DeadlyWorld{1.0.2} [Deadly World] (DeadlyWorld-1.7.10-1.0.2.jar) Unloaded->Constructed
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed
	EnderTech{1.7.10-0.3.2.388} [EnderTech] (EnderTech-1.7.10-0.3.2.388.jar) Unloaded->Constructed
	EnderZoo{1.7.10-1.0.11.28} [Ender Zoo] (EnderZoo-1.7.10-1.0.11.28.jar) Unloaded->Constructed
	emashercore{1.3.0.0} [ET Resources] (EngineersToolbox-1.2.0.5-BETA.jar) Unloaded
	emasherdefense{1.3.0.0} [ET Defense] (EngineersToolbox-1.2.0.5-BETA.jar) Unloaded
	eng_toolbox{1.2.0.5} [Engineer's Toolbox] (EngineersToolbox-1.2.0.5-BETA.jar) Unloaded
	gascraft{2.1.0.0} [GasCraft] (EngineersToolbox-1.2.0.5-BETA.jar) Unloaded
	enviromine{1.3.117} [EnviroMine] (EnviroMine-1.3.117.jar) Unloaded
	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded
	fastleafdecay{1.0} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.0.jar) Unloaded
	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) Unloaded
	gendustry{1.4.12.92} [GenDustry] (gendustry-1.4.12.92-mc1.7.10.jar) Unloaded
	GraveStone{2.12.3} [GraveStone] (GraveStone-2.12.3.jar) Unloaded
	HardcoreQuesting{The Journey (4.2.4)} [Hardcore Questing Mode] (HQM-The Journey (4.2.4).jar) Unloaded
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded
	launchgui{1.7.10-2.0-17} [LaunchGUI] (LaunchGui-1.7.10-2.0-17-client.jar) Unloaded
	MekanismGenerators{8.1.3} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.3.231.jar) Unloaded
	MekanismTools{8.1.3} [MekanismTools] (MekanismTools-1.7.10-8.1.3.231.jar) Unloaded
	millenaire{6.0.0} [Millénaire] (millenaire-6.0.0.jar) Unloaded
	minechem{5.0.5.398} [Minechem] (Minechem-1.7.10-5.0.5.398.jar) Unloaded
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded
	MobProperties{0.3.5} [Mob Properties] (MobProperties-1.7.10-0.3.5.jar) Unloaded
	modtweaker2{0.8.2} [Mod Tweaker 2] (ModTweaker 2-0.8.1.jar) Unloaded
	NEIAddons{1.12.9.32} [NEI Addons] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded
	NEIAddons|AppEng{1.12.9.32} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded
	NEIAddons|Botany{1.12.9.32} [NEI Addons: Botany] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded
	NEIAddons|Forestry{1.12.9.32} [NEI Addons: Forestry] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded
	NEIAddons|CraftingTables{1.12.9.32} [NEI Addons: Crafting Tables] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded
	NEIAddons|ExNihilo{1.12.9.32} [NEI Addons: Ex Nihilo] (neiaddons-1.12.9.32-mc1.7.10.jar) Unloaded
	neiintegration{1.0.9} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.9.jar) Unloaded
	Netherless{0.9.0} [Netherless] (Netherless-0.9.0.jar) Unloaded
	openmodularturrets{1.3.8} [Open Modular Turrets] (OpenModularTurrets-1.7.10-1.3.8-35.jar) Unloaded
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10h.jar) Unloaded
	ProjRed|Compatibility{4.6.2.82} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.6.2.82-Compat.jar) Unloaded
	ProjRed|Integration{4.6.2.82} [ProjectRed-Integration] (ProjectRed-1.7.10-4.6.2.82-Integration.jar) Unloaded
	ProjRed|Illumination{4.6.2.82} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.6.2.82-Lighting.jar) Unloaded
	ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2.jar) Unloaded
	simplyjetpacks{1.5.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.1.jar) Unloaded
	SpecialMobs{3.1.1} [Special Mobs] (SpecialMobs-1.7.10-3.1.1.jar) Unloaded
	SpiceOfLife{1.2.3} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.3.jar) Unloaded
	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) Unloaded
	StevesAddons{0.10.12} [Steve's Addons] (StevesAddons-1.7.10-0.10.12.jar) Unloaded
	StorageDrawers{1.7.10-1.5.3} [Storage Drawers] (StorageDrawers-1.7.10-1.5.3.jar) Unloaded
	StorageDrawersForestry{1.7.10-1.0.0} [Storage Drawers: Forestry Pack] (StorageDrawers-Forestry-1.7.10-1.0.0.jar) Unloaded
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded
	Translocator{1.1.2.15} [Translocator] (Translocator-1.7.10-1.1.2.15-universal.jar) Unloaded
	werkbench{1.2.56} [Werkbench] (Werkbench-1.7.10-1.2.56.jar) Unloaded
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	McMultipart{1.2.0.344} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded
	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) Unloaded
	ForgeMicroblock{1.2.0.344} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) Unloaded
	BiomeTweakerCore{0.9.97} [BiomeTweaker Core] (minecraft.jar) Unloaded->Disabled
	AE2 Version: stable rv2-stable-3 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GT 630/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Emasher** [comment]
Try upgrading to java 8, and let me know if it works.
Otherwise, I'll need a description of what you did to reproduce the crash.

Also, please pastebin crash reports.

**Comment by Beelzaboss** [comment]
Could you please add back support for java 1.7?

**Comment by Emasher** [comment]
I can look into it. For the moment, I'm not using any Java 8 specific features, so I'll see if I can do it easily. Why can't you just upgrade to Java 8 though?

**Comment by Frontrider** [comment]
i'm using java7, no issues.

**Comment by Emasher** [comment]
I suspect those of you experiencing the crash may have an outdated version of Java 7. Which versions are you all actually using?

**Comment by Beelzaboss** [comment]
I am using 1.8, But people on 1.7 crash on my private server, I am force to put a ugly red message on my private launcher to tell them to get 1.8 :(

**Comment by Emasher** [comment]
After a bit of investigation, it looks like all 1.7.10 builds have supported Java 7. The issue is that the class files that the Scala compiler generates don't support Java 7 versions older than a certain point. If you update to the latest version of Java 7, you should be able to run it fine.

That said, Oracle is no longer releasing new updates for Java 7, so you should all update to Java 8 anyway.
